from djongo import models

# Create your models here.
class User(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    study = models.CharField(max_length=100)
    YOP = models.CharField(max_length=50)
    number = models.CharField(max_length=50)
    CGPA = models.CharField(max_length=50)
    College = models.CharField(max_length=100)
    City = models.CharField(max_length=100)
    State = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    Interest = models.CharField(max_length=500)
class TeacherDetails(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    qual = models.CharField(max_length=100)
    pnumber = models.CharField(max_length=50)
    experience = models.CharField(max_length=500)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    dept = models.CharField(max_length=100)
    Specialization = models.CharField(max_length=500)
    display_name = models.CharField(max_length=500)
class BookTutor(models.Model):
    topic = models.CharField(max_length=100)
    tutorname = models.CharField(max_length=100)
    studentname = models.CharField(max_length=100)
    dateofthesession = models.CharField(max_length=100)
    starttime = models.CharField(max_length=100)
    totalduration = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    expectation = models.CharField(max_length=100)